name: Android CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          build-root-directory: HTTPShortcuts
          arguments: assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: http-shortcuts-debug-apk
          path: HTTPShortcuts/app/build/outputs/apk/debug/*.apk
